// Generated by CoffeeScript 1.7.1
(function() {
  var energyTypes, inputs, registerEvents, updateValues;

  energyTypes = [
    {
      name: "Joules",
      description: "The standard unit of energy",
      joules: 1,
      image: "jewel.png"
    }, {
      name: "Kilowatt Hours",
      description: "An industrial unit of energy",
      joules: 3600000,
      image: "meter.png"
    }, {
      name: "Hershey Kisses",
      description: "A popular chocolate candy",
      joules: 9e4,
      image: "hershey_kiss.png"
    }, {
      name: "Gasoline",
      description: "A gallon of standard gasoline",
      joules: 1.3e8,
      image: "gasoline.png"
    }, {
      name: "AA battery",
      description: "An AA battery",
      joules: 1.4e4,
      image: "aa_battery.png"
    }, {
      name: "Uranium-235",
      description: "A gram of Uranium-235",
      joules: 81570940000,
      image: "uranium.png"
    }, {
      name: "Dynamite",
      description: "A gram of dynamite",
      joules: 7.5e3,
      image: "dynamite.png"
    }, {
      name: "Lightbulb",
      description: "A 60-watt bulb running for one day",
      joules: 5184000,
      image: "lightbulb.png"
    }, {
      name: "Bullet",
      description: "Muzzle energy from one shot of a 9mm pistol",
      joules: 519,
      image: "bullet.png"
    }
  ];

  inputs = [];

  window.addEventListener('load', function() {
    var col, descCol, image, label, nameCol, numCol, row, table, type, _i, _j, _len, _len1, _ref;
    table = document.getElementById('energy-table');
    for (_i = 0, _len = energyTypes.length; _i < _len; _i++) {
      type = energyTypes[_i];
      row = document.createElement('tr');
      nameCol = document.createElement('td');
      image = document.createElement('img');
      image.src = "images/" + type.image;
      image.width = 100;
      image.height = 100;
      label = document.createElement('label');
      label.innerHTML = type.name;
      nameCol.appendChild(image);
      nameCol.appendChild(label);
      nameCol.style['text-align'] = 'center';
      descCol = document.createElement('td');
      descCol.innerHTML = type.description;
      numCol = document.createElement('td');
      type.input = document.createElement('input');
      inputs.push(type.input);
      numCol.appendChild(type.input);
      _ref = [nameCol, descCol, numCol];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        col = _ref[_j];
        row.appendChild(col);
      }
      table.appendChild(row);
    }
    registerEvents();
    return updateValues(100000);
  });

  registerEvents = function() {
    var i, type, _i, _len, _results;
    _results = [];
    for (i = _i = 0, _len = energyTypes.length; _i < _len; i = ++_i) {
      type = energyTypes[i];
      _results.push((function(type, i) {
        var change, event, _j, _len1, _ref, _results1;
        change = function() {
          var num;
          num = parseFloat(type.input.value);
          if (isNaN(num)) {
            num = 0;
          }
          return updateValues(num * type.joules, i);
        };
        _ref = ['change', 'keydown', 'paste', 'input'];
        _results1 = [];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          event = _ref[_j];
          _results1.push(type.input.addEventListener(event, change));
        }
        return _results1;
      })(type, i));
    }
    return _results;
  };

  updateValues = function(joules, idx) {
    var i, numVal, type, _i, _len, _results;
    if (idx == null) {
      idx = -1;
    }
    _results = [];
    for (i = _i = 0, _len = energyTypes.length; _i < _len; i = ++_i) {
      type = energyTypes[i];
      if (i === idx) {
        continue;
      }
      numVal = joules / type.joules;
      _results.push(inputs[i].value = numVal.toPrecision(10));
    }
    return _results;
  };

}).call(this);
