// Generated by CoffeeScript 1.7.1
(function() {
  var energyTypes;

  energyTypes = [
    {
      name: "Joules",
      description: "The standard unit of energy",
      joules: 1
    }, {
      name: "Hershey Kiss",
      description: "The amount of chemical energy in a hershey kiss",
      joules: 90000
    }
  ];

  window.addEventListener('load', function() {
    var col, descCol, input, inputs, nameCol, numCol, row, table, type, _i, _j, _len, _len1, _ref, _results;
    inputs = [];
    table = document.getElementById('energy-table');
    _results = [];
    for (_i = 0, _len = energyTypes.length; _i < _len; _i++) {
      type = energyTypes[_i];
      row = document.createElement('tr');
      nameCol = document.createElement('td');
      nameCol.innerHTML = type.name;
      descCol = document.createElement('td');
      descCol.innerHTML = type.description;
      numCol = document.createElement('td');
      input = document.createElement('input');
      inputs.push(input);
      numCol.appendChild(input);
      _ref = [nameCol, descCol, numCol];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        col = _ref[_j];
        row.appendChild(col);
      }
      _results.push(table.appendChild(row));
    }
    return _results;
  });

}).call(this);
